name: Reuse other workflow
on:  [workflow_dispatch]

jobs:
  call-workflow:
    uses: ./.github/workflows/reuseable.yml
    with:
      who-to-greet: '@jem-sudo'

  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "The time was ${{ needs.call-workflow.outputs.current-time }}"
      
